# Backend Dockerfile
FROM python:3.12-slim
WORKDIR /code
COPY ./app /code/app
COPY requirements.txt /code/requirements.txt
RUN pip install --upgrade pip && pip install -r /code/requirements.txt
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
